[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."resolve-maps"]
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/r/*"
  to = "/.netlify/functions/redirect/:splat"
  status = 200
  force = true
